#!/usr/bin/expect
log_user 0
set user [exec id -un]
set ip [lindex $argv 0]

if {[regexp {10\.100\.\d+.\d+} $ip]} {
    set dev_host ""
} else {
    set dev_host ""
}

spawn ssh $user@$dev_host
send "kinit\r"
expect "Password"
send "$env(MAGIC_NUMBER)\r"
send "ssh root@$ip\r"
interact
