#!/usr/bin/expect
log_user 0
set user [exec id -un]
set ip [lindex $argv 0]

if {[regexp "$env(VA_PATTERN)" $ip]} {
    set dev_host "$env(VA_DEV)"
} else {
    set dev_host "$env(SG_DEV)"
}

spawn ssh $user@$dev_host
send "kinit\r"
expect "Password"
send "$env(MAGIC_NUMBER)\r"
send "ssh root@$ip\r"
interact
