#!/usr/bin/expect
log_user 0
set user [exec id -un]
set ip [lindex $argv 0]
set dev_host "$env(CN_DEV)"

spawn ssh $user@$dev_host
send "kinit\r"
expect "Password"
send "$env(MAGIC_NUMBER)\r"
send "ssh root@$ip\r"
interact
