#!/usr/bin/expect
log_user 0
set user [exec id -un]
set remote_host [lindex $argv 0]

if {[regexp {\.\.\d+.\d+} $remote_host]} {
    set dev_host ""
} else {
    set dev_host ""
}

spawn ssh $user@$dev_host
send "b tiger\r"
send "ssh $remote_host\r"
interact
